Fix C tolower and signed char related undefined behavior
using libc shipped with cygwin,
 the build breaks with the following error message:

choices.c:25:3: error: array subscript has type 'char' [-Werror=char-subscripts]
   if (tolower(str[mstart]) == tolower(query[0])) {

Note: implementing tolower as a macro that does a lookup in
 an array - using the argument as an index - is a valid
 implementation according to the standard.

"the argument is an int, the value of which shall be representable as an
unsigned char or shall equal the value of the macro EOF.
If the argument has any other value, the behavior is undefined."